name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      Solution_Name: v2rayN\v2rayN.sln
      #Test_Project_Path: v2rayN\v2rayN\v2rayN.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: bin\v2rayN
      #Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 删除工作流运行
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1

    - name: Build
      shell: pwsh
      run:  cd v2rayN && 
        .\build.ps1 &&
        ls .\bin\v2rayN

    # - name: Package
    #   shell: pwsh
    #   run: |
    #     7z a -mx9 v2rayN.7z $env:Wap_Project_Directory


    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: v2rayN.zip
        path: ${{ env.Wap_Project_Directory }}

      
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        prerelease: ${{ contains(github.ref, '-') }}
        draft: false
        files: |
            v2rayN.7z
        body: |
            [![](https://img.shields.io/badge/Telegram-Channel-blue)](https://t.me/netch_channel) [![](https://img.shields.io/badge/Telegram-Group-green)](https://t.me/netch_group)
            ## Changelogs
            * This is an automated deployment of GitHub Actions, the change log should be updated manually soon
            
            ## 更新日志
            * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新